// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrhEZelQLer7NZ6nn0Cg57Gs7CImV0CbM',
    appId: '1:767896169017:web:70e1554f85edc0b9fb7be8',
    messagingSenderId: '767896169017',
    projectId: 'facturadoroff',
    authDomain: 'facturadoroff.firebaseapp.com',
    storageBucket: 'facturadoroff.firebasestorage.app',
    measurementId: 'G-072D4Z43S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4aPx1JBtUPksAOIqY3UvBiiaWpXFW4N8',
    appId: '1:767896169017:android:f06d42294f66e500fb7be8',
    messagingSenderId: '767896169017',
    projectId: 'facturadoroff',
    storageBucket: 'facturadoroff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe0dpxrRMnvYMcHXNVOwirtpeama0A82A',
    appId: '1:767896169017:ios:7132a455e9ee9812fb7be8',
    messagingSenderId: '767896169017',
    projectId: 'facturadoroff',
    storageBucket: 'facturadoroff.firebasestorage.app',
    iosBundleId: 'com.ultrix.facturadorOffline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe0dpxrRMnvYMcHXNVOwirtpeama0A82A',
    appId: '1:767896169017:ios:7132a455e9ee9812fb7be8',
    messagingSenderId: '767896169017',
    projectId: 'facturadoroff',
    storageBucket: 'facturadoroff.firebasestorage.app',
    iosBundleId: 'com.ultrix.facturadorOffline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrhEZelQLer7NZ6nn0Cg57Gs7CImV0CbM',
    appId: '1:767896169017:web:0b0ff28b0dd8acecfb7be8',
    messagingSenderId: '767896169017',
    projectId: 'facturadoroff',
    authDomain: 'facturadoroff.firebaseapp.com',
    storageBucket: 'facturadoroff.firebasestorage.app',
    measurementId: 'G-D5S0Z8BGSR',
  );
}
